config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/random_joke' => 'home#random_joke'
  get 'home/random_quote' => 'home#random_quote'
  

  resources :jokes
  resources :quotes

end

app/models/joke.rb
class Joke < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @jokes = Joke.all
    @quotes = Quote.all
  end
  
  def random_joke
    @joke = Joke.all[rand(Joke.count)]
  end

  def random_quote
    @quote = Quote.all[rand(Quote.count)]
  end
  
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def create
    Joke.create(joke_params)
    redirect_to jokes_path
  end
  
  def destroy
    @joke = Joke.find(params[:id])
    @joke.destroy
    redirect_to jokes_path
  end
  
  def edit
    @joke = Joke.find(params[:id])
  end
  
  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all
    @joke = Joke.new
  end
  
  # GET /resources/new
  def new
    @joke = Joke.new
  end
  
  def update
    @joke = Joke.find(params[id])
    @joke.update_attributes(joke_params)
    redirect_to jokes_path
  end
  
  private
  
  def joke_params
    params.require(:joke).permit(:body)
  end
end  # class JokesController < ApplicationController

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def create
    Quote.create(quote_params)
    redirect_to quotes_path
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    redirect_to quotes_path
  end
  
  def edit
    @quote = Quote.find(params[:id])
  end
  
  def index
    @quotes = Quote.all
  end
  
  def new
    @quote = Quote.new
  end
  
  def update
    @quote = Quote.find(params[:id])
    @quote.update_attributes(quote_params)
    redirect_to quotes_path
  end
  
  private
  
  def quote_params
    params.require(:quote).permit(:body)
  end
end  # class QuotesController < ApplicationController

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/home/_buttons.html.erb
<table>
  <tr>
    <td><%= button_to 'Pearl of Wisdom', home_random_quote_path, :id => "btn-rand-quote", remote: true, method: :get %></td>
    <td><%= button_to 'Click for a Funny', home_random_joke_path, :id => "btn-rand-joke", remote: true, method: :get %></td>
  </tr>
</table>

app/views/home/_nav.html.erb
<table>
  <tr>
    <td><%= link_to "Main", root_path %></td>
    <td><%= link_to "Jokes Menu", jokes_path %></td>
    <td><%= link_to "Quotes Menu", quotes_path %></td>
  </tr>
</table>

app/views/home/index.html.erb
<div id='payload_body'>
<%= render "buttons" %>
<%= render "nav" %>

app/views/home/random_joke.html.erb
<p><%= @joke.body %></p>

<%= render "buttons" %>
<%= render "nav" %>

app/views/home/random_quote.html.erb
<p><%= @quote.body %></p>

<%= render "buttons" %>
<%= render "nav" %>

app/views/jokes/_form.html.erb
<%= form_for(@joke, remote: true) do |j| %>
  <div>
    <%= j.label :body %>
    <%= j.text_area :body, size: '60x6' %>
  </div>
  <div>
    <%= j.submit %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Edit Joke</h1>

<%= render "form" %>

app/views/jokes/index.html.erb
<h1>Jokes Index Page</h1>
<%= render "form" %>
<% @jokes.each do |joke| %>
  <table>
    <tr>
      <td><%= joke.body %></td>
      <td><%= link_to "Edit", edit_joke_path(joke) %></td>
      <td><%= link_to "Delete", joke, method: :delete %></td>
    </tr>
  </table>
<% end %>

<%= render "home/nav" %>

app/views/jokes/new.html.erb
<h1>Add a joke</h1>

<%= form_for @joke do |j| %>
  <div>
    <%= j.label :body %>
    <%= j.text_area :body, size: '60x6' %>
  </div>
  <div>
    <%= j.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote do |q| %>
  <div>
    <%= q.label :body %>
    <%= q.text_area :body, size: '60x6' %>
  </div>
  <div>
    <%= q.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>

<%= render "form" %>

app/views/quotes/index.html.erb
<h1>Quotes Index Page</h1>
<%= link_to "Add a Quote", new_quote_path %>
<% @quotes.each do |quote| %>
  <table>
    <tr>
      <td><%= quote.body %></td>
      <td><%= link_to "Edit", edit_quote_path(quote) %></td>
      <td><%= link_to "Delete", quote, method: :delete %></td>
    </tr>
  </table>
<% end %>

<%= render "home/nav" %>

app/views/quotes/new.html.erb
<h1>Add a quote</h1>

<%= render "form" %>